version: '3.7'

services:
  web:
    build: .
    command: bash -c "/wait && sh ./boot.sh"
    depends_on:
      - redis
    links:
      - redis
    environment:
      - WAIT_HOSTS=redis:6379
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    volumes:
      - .:/app
    ports:
      - 8080:80
    networks:
      - backend
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - 6379:6379
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
